version: "3"
services:
  web:
    build:
      context: ./web
    volumes:
      - ./web:/code
  locust:
    image: grubykarol/locust
    container_name: locust2
    ports:
      - "8064:8089"
    environment:
      ATTACKED_HOST: "http://web:80"
      LOCUST_OPTS: "--no-web -c 5 -r 10"
    volumes:
      - ./locust:/locust
