# Generated by Django 3.0.8 on 2020-08-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries_app', '0003_auto_20200729_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statline',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries_app.Game'),
        ),
    ]
