version: "3"
services:
  web:
    build:
      context: ./app
    volumes:
      - ./app/code:/code
    ports:
      - "8051:5000"
    depends_on:
      - redis
      - mongo
      - postgres
    stdin_open: true
    tty: true
  redis:
    image: redis
  mongo:
    image: mongo
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: notverysecret
